use_frameworks!

platform :ios, '8.0'

target 'FFUpdateSDK-iOS_Example' do
  pod 'FFUpdateSDK-iOS', :path => '../'

  target 'FFUpdateSDK-iOS_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
